### ISSUE TITLE
Helm redis port resolves to null

### ISSUE THREAD

**Issue by githubcdr** [FikaWorks/helm-charts#30]
Hi There,

We noticed that the chart creates an invalid redis-url secrets when there is no value for {{_.Values.redis.master.service.port_}}, perhaps a bitnami upstream issue. (ValueError: Port could not be cast to integer value as '%!f(<nil>)')

https://github.com/FikaWorks/helm-charts/blob/master/charts/kodiak/templates/_helpers.tpl#L70

adding master scope fixed it for us;

```
redis:
  enabled: true
  image:
    tag: "7.0"
  podSecurityPolicy:
    create: false
    enabled: false
  master:
    service:
      port: 6379
```

Best regards ;)
